'use strict';

module.exports.translate_en = {
	  "se connecter": "Log in",
	  "s'inscrire": "Sign up",
	  "se déconnecter": "Logout",
	  "titre": "Title",
	  "complexite": "Complexity",
	  "fraicheur": "Freshness",
	  "type": "Content type",
	  "interet": "Interest",
	  "commentaire": "Comment",
	  "aide": "Help",
	  "paramétres": "Account settings",
	  "compte": "Account",
	  "mes annotations": "My Annotations",
	  "vous devez être connecté pour créer des annotations.": "You must be logged in to create annotations.",
	  "pas d'informations sur cette annotation": "No information for this annotation",
	  "sauvegarde": "Saving...",
	  "chercher": "Search",
	  "deposée par": "Deposited by",
	  "en": "in",
	  "il n'y a pas de notes de page dans ce groupe.": "There are no page notes in this group.",
	  "créez-en un en cliquant sur le" : "Create one by clicking on",
	  "bouton": "button",
	  "créez-en un en sélectionnant du texte et en cliquant sur le": "Create one by selecting text and clicking on the",
	  "poster à": "Post to",
	  "annuler": "Cancel",
	  "modifier": "Edit",
	  "effacer": "Delete",
  	  "partager": "Share",
	  "répondre": "Reply",
	  "moi uniquement": "Me Only",
	  "Position": "Position",
	  "Ancienne": "Oldest",
	  "Récente": "Newest",
	  "Tweet lien": "Tweet link",
	  "Partager sur Facebook": "Share on Facebook",
	  "Publier sur Google Plus": "Share on Google Plus",
	  "Partager par email": "Share on email",
	  "Partager sur Plazza": "Share on Plazza"
};

module.exports.translate_fr = {
	  "se connecter": "Se connecter",
	  "s'inscrire": "S'inscrire",
	  "se déconnecter": "Se déconnecter",
	  "titre": "Titre",
	  "complexite": "Complexité",
	  "fraicheur": "Fraicheur",
	  "type": "Type de contenus",
	  "interet": "Intérêt",
	  "commentaire": "Commentaire",
	  "aide": "Aide",
	  "paramétres": "Paramétres du compte",
	  "compte": "Compte",
	  "mes annotations": "Mes Annotations",
	  "vous devez être connecté pour créer des annotations.": "Vous devez être connecté pour créer des annotations.",
	  "pas d'informations sur cette annotation": "Pas d'informations sur cette annotation",
	  "sauvegarde": "Sauvegarde...",
	  "chercher": "Chercher",
	  "deposée par": "Deposée par",
	  "en": "en",
	  "il n'y a pas de notes de page dans ce groupe.": "Il n'y a pas de notes de page dans ce groupe.",
	  "créez-en un en cliquant sur le" : "Créez-en un en cliquant sur le",
	  "bouton": "bouton",
	  "créez-en un en sélectionnant du texte et en cliquant sur le": "Créez-en un en sélectionnant du texte et en cliquant sur le",
	  "poster à": "Poster à",
	  "annuler": "Annuler",
	  "modifier": "Modifier",
	  "effacer": "Effacer",
  	  "partager": "Partager",
	  "répondre": "Répondre",
	  "moi uniquement": "Moi Uniquement",
	  "Position": "Position",
	  "Ancienne": "Ancienne",
	  "Récente": "Récente",
	  "Tweet lien": "Tweet lien",
	  "Partager sur Facebook": "Partager sur Facebook",
	  "Publier sur Google Plus": "Publier sur Google Plus",
	  "Partager par email": "Partager par email",
	  "Partager sur Plazza": "Partager sur Plazza"
};
